import Head from 'next/head';
import Image from 'next/image';
import styles from '../styles/Home.module.css';
import Header from './components/Header';
import Footer from './components/Footer';
import Hero from './components/Hero';
import WeeklyTrends from './components/WeeklyTrends';

export default function Home() {
  return (
    <>
      <Head>
        <title>NFT KING</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="robots" content="index, follow" />
        <meta name="revisit-after" content="15 days" />
        <meta name="author" content="Nizamettin Şimşek" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />
      <hr className="bg-[#333333]" />
      <Hero />
      <WeeklyTrends />

      <Footer />
    </>
  );
}
